[package]
name = "f2png-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
eframe = { version = "0.24", features = ["glow"] }
egui = "0.24"
rfd = "0.14"
f2png-core = { path = "../f2png-core" }
image.workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["windef", "winuser"] }
